my.greeting: Hello
app:
  name: My applic
  description: Welcome to ${app.name}

my:
  list:
    values: One,Two,Three
  db:
    mapValues: "{connectionUrl:'http://skdfsl/sdkf', userName: 'foo', pasword: 'pass'}"

#db:
#  connection: "test-connection-string"
#  host: 127.0.0.1
#  port: 2400

management.endpoints.web.exposure.include: "*"