my.greeting: Hello
app:
  name: My applic
  description: Welcome to ${app.name}

my:
  list:
    values: One,Two,Three
  db:
    mapValues: "this is application.yml connection"

#db:
#  connection: "application connection string"
#  host: 127.0.0.1
#  port: 1200

spring.application.name: sprint
management.endpoints.web.exposure.include: "*"

spring.profiles.active: test

spring.cloud.config.uri: http://localhost:8888